### ISSUE TITLE
Overflipping allows any equal number of a different suit to be flipped as trump

### ISSUE THREAD

**Issue by EmptyCrown** [rbtying/shengji#101]
Say we're playing 4's. If someone flips two 4 of spades, anyone can flip two 4 of diamonds or two 4 of clubs, etc. The first flip should block out the rest?

**Comment by rbtying** [comment]
This was a recent change, to allow people who play with alternative bidding styles -- in particular, there are people who play with a lazy-reinforce mechanism, e.g. allowing the person who played the first 4 to reinforce and preempt another person playing two fours.

It should be possible to flip back, though, to support the default style?

**Comment by EmptyCrown** [comment]
Don't think so? We weren't able to revert after someone else flipped a new suit.

**Comment by rbtying** [comment]
Hm. Do you mind telling me more about the sequence of bids? There's an explicit test for it, here: https://github.com/rbtying/shengji/blob/master/core/src/game_state.rs#L1308

If the bid was a pair of jokers, that overrides a pair of 4s

**Comment by EmptyCrown** [comment]
I believe the sequence is like

One 4 of diamonds -> Two 4's of spades -> Two 4's of clubs

At this point, it wasn't possible to revert back to the spades (I believe?). Jokers, of course, can always be overflipped on top, but just concerning the 4's, a pair shouldn't be able to be flipped on another pair. If it's made possible to allow for custom rules, then an "undo" should be possible.
