### ISSUE TITLE
Bidding should only be allowed with more number of cards

### ISSUE THREAD

**Issue by blu-world** [rbtying/shengji#119]
In Finding Friends, when P1 makes a bid with 22, should it limit the subsequent bid to either 222 or at least two Jokers?
Currently when someone bid 22 of CLubs and next Player can bids 22 of Hearts and the end result is the Hearts become the Trump card instead of Clubs

**Comment by rbtying** [comment]
@blu-world this was changed at one point to allow more bidding strategies (i.e. not just increasing in the number of cards). Now that there's a take back bid button, we can return to the prior behavior and have nonstandard bidding coordinate externally

**Comment by blu-world** [comment]
I see. Thx!
