### ISSUE TITLE
Penalty option for a bad throw

### ISSUE THREAD

**Issue by asonglin** [rbtying/shengji#135]
If a bad first-hand throw contains several sets of cards, such as singles, pairs or tractors, the option should enforce the beatable component to be placed in current round. For example, a throw contains a small pair and an ‘A’. The small pair should be enforced in current round, which could lose to another player. If all cards are singles, the smallest one should be enforced.

**Comment by rbtying** [comment]
There's already an implementation for this -- when the player mis-throws, you can keep playing (the big cards are the part that are automatically played). You'll need to avoid people taking back their trick via social cues, though!
