### ISSUE TITLE
[Bug] Only "th" is showing on screen display when setting 4th card of the same suit

### ISSUE THREAD

**Issue by Claire-Zheng** [rbtying/shengji#139]
This issue is when 7 people playing with 4 decks of cards.

When the leader sets down the 4th card of the same suit (e.g. the 4th spade A), the number 4 is missing, only "th" is displayed on everyone's screen (should be "4th").

**Comment by cai-jack** [comment]
fixed. please verify and close

**Comment by Claire-Zheng** [comment]
Fixed. Thanks!
