### ISSUE TITLE
UI/API for specifying throw breakdowns when parse is ambiguous, e.g. [2, 2, 2, 3, 3]

### ISSUE THREAD

**Issue by Claire-Zheng** [rbtying/shengji#142]
Have an option (perhaps in game settings) to play a consecutive double + triple (e.g. [2, 2, 2, 3, 3], or [7, 7, 8, 8, 8]).

**Comment by rbtying** [comment]
Curious:

is [2,2,2,3,3] a throw of [2,2,2], [3,3], or is it a new play-format entirely (=non-rectangular tractor)?

there's a known issue right now where the UI / API doesn't support specifying throw-breakdowns when it should, so [2,2,2,3,3] is always interpreted as [2,2,3,3], [2]. Fixing that has been ~low priority but should be done at some point (the backend updates are easy, but there's a decent amount of frontend work to build a UI for selecting groups).

**Comment by Claire-Zheng** [comment]
Yeah, [2, 2, 2, 3, 3] is a throw of [2, 2, 2], [3, 3].

And no worries - definitely not essential by any means!

**Comment by rbtying** [comment]
It's a fun starter task if you have any interest in hacking on the code :)

**Comment by Claire-Zheng** [comment]
I was planning to try! Will probably have to brush up on some Rust and learn how to play the game from my parents first though haha
