### ISSUE TITLE
option to set landlord emoji as a game setting option

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#154]
other than just 当庄

my friends are heart broken when the little pig is removed in trick list:)

so I decided to give it a big kahuna treatment, with this new function, users can pick an emoji from the emoji list and be whatever pig and more they want to be :)

I will check in the code using the same pull requests as #145 

![Screen Shot 2020-06-21 at 2 30 22 PM](https://user-images.githubusercontent.com/4054100/85235682-e5998d00-b3cb-11ea-8ce4-53a6389f3590.png)

**Comment by rbtying** [comment]
oh, interesting! I'd actually replaced it mostly because it made the line-height awkward, but I found a way to fix that in CSS, It hink.

Is this emoji-selector stored clientside or serverside ?

**Comment by cai-jack** [comment]
client side. server uses string

**Comment by cai-jack** [comment]
emoji-picker-react

**Comment by cai-jack** [comment]
the line-height fix works pretty well
