### ISSUE TITLE
user option to separate bid cards during Draw stage

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#158]
putting bid cards with the rest of the hand during draw makes it difficult to pick the bid cards when cards are constantly added, leading to many incorrect picks and missed opportunities.

this user option allows to individual player to move the bid cards above the rest of the hand so that picking the cards to bid is simpler

**Comment by rbtying** [comment]
curious: have you tried sorting the cards the other way?

**Comment by cai-jack** [comment]
No. should I? Take a look at the screen shot and let me know.

**Comment by rbtying** [comment]
oh, no -- I just meant; if you sort the cards in reverse order, the bid cards are in a fixed location

**Comment by cai-jack** [comment]
I see. that will indeed fix the bidding nuance, but then the order of the cards during play will be in reverse order, so this may still be useful so we can still keep the order during play?

**Comment by rbtying** [comment]
I'm not against having your change, to be clear! Just wanted to point out that there was already a solution for this :)

**Comment by cai-jack** [comment]
Ok. Thanks:) Please review as I have to deal with when landlord is not selected yet again.
