### ISSUE TITLE
Add an option for protecting tractors

### ISSUE THREAD

**Issue by cmanaog** [rbtying/shengji#165]
It would be nice to have an option to prevent tractors from being broken if there is another valid play. 

For example, supposed the player going second in turn order has  [2, 3, Q, Q, K, K] in spades, and the first player plays a pair of spades, then the second player with the tractor can protect their tractor from being broken by playing [2, 3]. However, if the next round, the first player plays another pair of spades, then tractor are the last spades in that person's hand, they will need to break their tractor.

**Comment by rbtying** [comment]
Interesting! this is not a rule variant I've played with before. In this ruleset, are triples also protected against tractors?

**Comment by rbtying** [comment]
This was implemented a while back
