### ISSUE TITLE
Option to allow players to "steal the kitty"

### ISSUE THREAD

**Issue by carlgao** [rbtying/shengji#17]
Once Landlord has taken the kitty and set it down, **other** players in turn order may over-declare aka over-flip to a new trump suit, following standard over-flipping rules, to both change the trump suit and access the kitty. Exception: if you were the one whose declaration is the currently active, you may not over-flip your own declaration. 

If over-flipping doesn't occur, the game immediately starts as normal. 

If over-flipping occurs, after the kitty is set back down again, all of the players besides the over-flipper, **including the landlord**, may yet again over-flip, following the same rules, in turn order starting from after the over-flipper. And so on. 

So this is possible:
1. Landlord declares clubs by revealing a 2 of clubs
2. Landlord reinforces by adding a second 2 of clubs
3. Landlord takes kitty, swaps cards, and puts it down
4. The player who goes after the landlord (player A) over-flips by revealing a pair of 2 of hearts; then takes kitty, swaps cards, and puts it down
5. After confirming the other 2 players in turn order will not over-flip, it becomes Landlord's turn to over-flip if able. Landlord over-flips by revealing a pair of Little Jokers. Takes the kitty, swaps cards, then puts it down
6. Player A over-flips by revealing a pair of Big Jokers. Takes kitty, swaps cards, puts it down. 
7. Nothing can over-flip Big Jokers so the game begins with Landlord leading.

Issues to resolve:
1. I don't know how we'd take care of the edge case of no one declaring, but regardless if no one declares you can only flip with small and big joker, and not the other cards anymore
2. If it's 3 decks people feel differently on how people should be able to flip with jokers...

**Comment by rbtying** [comment]
1. Hm. The current handling for nobody declaring is that the game just sits there, waiting for somebody to bid. I think that we can retain that behavior (the reveal-a-card-from-the-kitty thing seems less good).

2. the current implementation only allows over-declaring a trump suit to some other trump suit if there are strictly more cards, or the same number of cards if it is trump -> no trump. while this is definitely something that can be potentially configured, it is probably easiest to retain that functionality when we first implement the kitty-stealing operation

This isn't a house rule that I personally play with, so I'm not very familiar with it. thoughts?
