### ISSUE TITLE
couldn't read backend/src/../../frontend/dist/main.js:

### ISSUE THREAD

**Issue by chnlyi** [rbtying/shengji#177]
Running into this issue after "cargo run", any thought?

   Compiling warp v0.2.2
error: couldn't read backend/src/../../frontend/dist/main.js: No such file or directory (os error 2)
   --> backend/src/main.rs:684:19
    |
684 | static JS: &str = include_str!("../../frontend/dist/main.js");
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read backend/src/../../frontend/dist/async.js: No such file or directory (os error 2)
   --> backend/src/main.rs:686:25
    |
686 | static ASYNC_JS: &str = include_str!("../../frontend/dist/async.js");
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read backend/src/../../frontend/dist/playing-cards.js: No such file or directory (os error 2)
   --> backend/src/main.rs:688:25
    |
688 | static CARDS_JS: &str = include_str!("../../frontend/dist/playing-cards.js");
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read backend/src/../../frontend/dist/main.js.map: No such file or directory (os error 2)
   --> backend/src/main.rs:690:23
    |
690 | static JS_MAP: &str = include_str!("../../frontend/dist/main.js.map");
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

error: could not compile `shengji`.

**Comment by rbtying** [comment]
At a guess, you need to `cd frontend && yarn build` or `cd frontend && yarn watch`? These files are compiled frontend code.

If you're doing local development, you may want to use the `cargo run --features dynamic` flag, which lazily loads the corresponding files.

**Comment by chnlyi** [comment]
After running "cd frontend && yarn run build", it worked. Thanks a lot!

Just in case anyone running into some problem with yarn and webpack, I had to reinstall my yarn and do this: "yarn add webpack webpack-dev-server --dev --ignore-engines" too.
