### ISSUE TITLE
missing bigJoker?

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#182]
I have noticed a number of times during testing, one bigjoker is missing in the combined cards of all players. A bug in  card gen? here is the game state dump:

{"aaaabbbbccccdddd":{"Play":{"num_decks":2,"game_mode":{"FindingFriends":{"num_friends":1,"friends":[{"card":"🃎","skip":0,"initial_skip":0,"player_id":0}]}},"propagated":{"game_mode":{"FindingFriends":{"num_friends":null}},"hide_landlord_points":false,"kitty_size":null,"friend_selection_policy":"HighestCardNotAllowed","num_decks":null,"max_player_id":4,"players":[{"id":0,"name":"test1","level":"2","metalevel":1},{"id":1,"name":"test2","level":"2","metalevel":1},{"id":2,"name":"test3","level":"2","metalevel":1},{"id":3,"name":"test4","level":"2","metalevel":1}],"observers":[],"landlord":1,"landlord_emoji":"🙆","chat_link":null,"advancement_policy":"Unrestricted","kitty_penalty":"Power","throw_penalty":"None","hide_played_cards":true,"num_games_finished":0,"kitty_bid_policy":"FirstCardOfLevelOrHighest","kitty_theft_policy":"NoKittyTheft","trick_draw_policy":"LongerTuplesProtected","throw_evaluation_policy":"Highest","first_landlord_selection_policy":"ByFirstBid","bid_policy":"GreaterLength","bonus_level_policy":"BonusLevelForSmallerLandlordTeam","play_takeback_policy":"NoPlayTakeback","bid_takeback_policy":"NoBidTakeback","game_shadowing_policy":"SingleSessionOnly"},"hands":{"hands":{"1":{"🃞":1,"🃊":1,"🃖":1,"🃋":1,"🃛":1,"🂺":1,"🂤":1,"🂹":1,"🃚":1,"🂴":1,"🃑":1,"🂧":1,"🂲":1},"2":{"🃚":1,"🂾":2,"🃕":2,"🃙":2,"🃁":1,"🃂":1,"🂵":1,"🃗":1,"🂢":1,"🂽":1},"3":{"🃊":1,"🂮":1,"🃘":1,"🂩":1,"🂲":1,"🂵":1,"🃗":1,"🃎":1,"🂷":1,"🂶":1,"🃒":1,"🂥":1,"🃓":1},"0":{"🃂":1,"🃉":1,"🃟":1,"🃄":1,"🃝":2,"🃋":1,"🃍":1,"🂺":1,"🃛":1,"🃃":1,"🂢":1,"🃑":1,"🂻":1}},"trump":{"Standard":{"suit":"♧","number":"2"}}},"points":{"3":["🃎","🂪"],"0":[],"1":["🃅","🃅","🂥","🂪","🂮"],"2":[]},"penalties":{"2":0,"0":0,"3":0,"1":0},"kitty":["🃉","🃆","🃒","🂴","🂩","🃘","🃏","🂱"],"landlord":1,"landlords_team":[1,0],"trump":{"Standard":{"suit":"♧","number":"2"}},"trick":{"player_queue":[0],"played_cards":[{"id":1,"cards":["🃔"],"bad_throw_cards":[],"better_player":null},{"id":2,"cards":["🃟"],"bad_throw_cards":[],"better_player":null},{"id":3,"cards":["🃞"],"bad_throw_cards":[],"better_player":null}],"played_card_mappings":[[{"Repeated":{"count":1,"card":{"card":"🃔","trump":{"Standard":{"suit":"♧","number":"2"}}}}}],[{"Repeated":{"count":1,"card":{"card":"🃟","trump":{"Standard":{"suit":"♧","number":"2"}}}}}],[{"Repeated":{"count":1,"card":{"card":"🃞","trump":{"Standard":{"suit":"♧","number":"2"}}}}}]],"current_winner":2,"trick_format":{"suit":"Trump","trump":{"Standard":{"suit":"♧","number":"2"}},"units":[{"Repeated":{"count":1,"card":{"card":"🃔","trump":{"Standard":{"suit":"♧","number":"2"}}}}}]},"trump":{"Standard":{"suit":"♧","number":"2"}}},"last_trick":{"player_queue":[],"played_cards":[{"id":1,"cards":["🃈","🃈"],"bad_throw_cards":[],"better_player":null},{"id":2,"cards":["🃇","🃇"],"bad_throw_cards":[],"better_player":null},{"id":3,"cards":["🃆","🃍"],"bad_throw_cards":[],"better_player":null},{"id":0,"cards":["🃅","🃅"],"bad_throw_cards":[],"better_player":null}],"played_card_mappings":[[{"Repeated":{"count":2,"card":{"card":"🃈","trump":{"Standard":{"suit":"♧","number":"2"}}}}}],[{"Repeated":{"count":2,"card":{"card":"🃇","trump":{"Standard":{"suit":"♧","number":"2"}}}}}],null,[{"Repeated":{"count":2,"card":{"card":"🃅","trump":{"Standard":{"suit":"♧","number":"2"}}}}}]],"current_winner":1,"trick_format":{"suit":"Diamonds","trump":{"Standard":{"suit":"♧","number":"2"}},"units":[{"Repeated":{"count":2,"card":{"card":"🃈","trump":{"Standard":{"suit":"♧","number":"2"}}}}}]},"trump":{"Standard":{"suit":"♧","number":"2"}}},"exchanger":null}}}

**Comment by rbtying** [comment]
hm. can you write a test to reproduce? I have literally never encountered this.

**Comment by cai-jack** [comment]
difficult to reproduce. I noticed this only when I was test playing, missing joker is the most noticeable. Never happened during actually play though

**Comment by rbtying** [comment]
Going to close this for now, unless we can find a way to reproduce it
