### ISSUE TITLE
Semantics of successfully defending A in "Finding Friends" game?

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#190]
for a player to be said to defend A successfully, our understanding is the player should be the landlord, not just on the landlord team. This is mainly a problem with the "Finding Friends" style of playing, since landlord team players can have different ranks.

**Comment by rbtying** [comment]
Hm. I think this is up to interpretation, but my mind has been; if you are on the team, you started on A, and you go up a level, it counts -- this is consistent with fixed-team semantics, where either player successfully landlord-ing on A counts.

WDYT?

**Comment by cai-jack** [comment]
That is one way of seeing it. It just feels weird to us when the landlord won on say, 7, and the other team player got a congrats on defending A :)

Any objection of me adding an option to only allow landlord to win on defending A, for the finding friend style only?

**Comment by rbtying** [comment]
ah, I see. fair enough. We can change the default here, so that (at least) the landlord has to defend A
