### ISSUE TITLE
Add ping/beep option when the dealer is picking cards from the bottom pile

### ISSUE THREAD

**Issue by emsiu** [rbtying/shengji#204]
Love this. Having loads of fun with the fam. Thanks for creating and sharing it!

**Comment by rbtying** [comment]
Easy enough to add! but... also why :)

**Comment by emsiu** [comment]
Sometimes the dealer might not notice that it's actually time to pick cards from the bottom pile, so a ping would notify them to take action.

Also, if the dealer is taking a long time to sort their hand, then it would be nice for other players to ping them with a gentle reminder to hurry up, just like we have the option to beep during each trick :)
