### ISSUE TITLE
Add sound effect to drawing cards

### ISSUE THREAD

**Issue by emsiu** [rbtying/shengji#217]
Feels more satisfying to hear the draw of a card while playing!

**Comment by rbtying** [comment]
@emsiu any suggestions on the sound?

I am generally hesitant to incorporate more static assets (they make the page load slower), but if we can come up with something reasonable with a chiptune or embed something pretty small, this might be fun

**Comment by emsiu** [comment]
Perhaps something like this? https://freesound.org/people/dersuperanton/sounds/434472/
