### ISSUE TITLE
Allow more step sizes and offsets for custom scoring

### ISSUE THREAD

**Issue by chnlyi** [rbtying/shengji#222]
Liked the recent changes for  #221! The colored bar is my favorite!

However, would it be more intuitive to define the step/steps as points plus or minus the defeating point?  also, can more steps (20 30 40 50 60 70 80 90 100) be added?

For example, if there are 5 guys playing 2 decks, first, they define the defeating point as 90 (not 80 because they feel landlord only has one friend, or whatever...); then they want to increase the speed of shengji so that they define the step to be 30 instead of 40. Now the tie (no side advance) will be 90 to 120; landlord advances 1 level when the score is between 60 and 85; attacking advances 1 level when the score is between 120 and 150; landlord advances 2 levels when the score is between 30 and 55; attacking advances 2 levels when the score is between 150 and 180; etc

**Comment by rbtying** [comment]
Worth considering! The main issue I ran into was that the default scoring is not actually just linear in steps: it's not 0-35, 40-75, 80-115, 120-155, 160-195, 200; it's actually 0, 5-35, ...

As a result, people are likely going to be surprised if either 0 is treated specially (potentially truncating the first step by more than 5 points, if the offset is allowed) or if it isn't (doesn't map to the default game well).

So, the initial pass was to only allow step sizes which evenly divide 100, and to force steps to start at zero. Curious to hear your thoughts on what the "right" zero-crossing / max-points-crossing behavior would be

**Comment by xiaofan-iit** [comment]
Would support more flexibility of step sizes around the default value. For example, for 3 decks of cards, the default size is 60; could you add 50, 55, 65, 70 as choices of step size? Similarly, for other numbers of decks. The reason for the suggestion is that the number of players, the number of friends and the number of bottom cards change. Thus, we would like to adjust the step size around the default value (up and down upto 15 points). Thanks.

**Comment by rbtying** [comment]
@xiaofan-iit that makes sense -- the current limitation was predominantly to make it so that the scoring scales with the number of decks (so, the step-size is the number of decks multiplied by a deck-invariant step). It also currently requires that the deck-invariant step evenly divides a single deck.

Do you mind filing another issue for that? I think it's a different issue

**Comment by xiaofan-iit** [comment]
@rbtying Thanks for your consideration. I will file as a different issue (if I can find how to file a new issue:)).
