### ISSUE TITLE
Implement configurable scoring

### ISSUE THREAD

**Issue by blu-world** [rbtying/shengji#224]
Not sure if this is completed or not. But when I click on "open" for "Scoring Settings:", it just shows a blank screen.

**Comment by rbtying** [comment]
ahh, this is a bug. let me look into it.

**Comment by rbtying** [comment]
it looks like there's a bug in the config screen when there aren't at least 4 players -- I will fix.

try the scoring settings when everyone has joined? you can also test by self-joining in multiple tabs or windows in your browser
