### ISSUE TITLE
Don't require A to be defended to cross "A"

### ISSUE THREAD

**Issue by chnlyi** [rbtying/shengji#226]
Can you add a feature to circle back to "2" after reaching "A" with a round number of 2?

**Comment by rbtying** [comment]
The current logic is that the landlord needs to successfully *defend* on A (i.e. be landlord and win) to pass A -- i.e. you can't go from K to 2, and the attacking team can't go past A at all.

Did you encounter a situation where successfully defending on A didn't wrap around properly to 2^2?

**Comment by chnlyi** [comment]
Sorry, we didn't face that. 
Can you add an option so that it's not necessary to defend "A" to advance to next round?
