### ISSUE TITLE
Print out the cards from the bottom pile after the game has ended in chat

### ISSUE THREAD

**Issue by emsiu** [rbtying/shengji#228]
Found that sometimes we miss seeing what cards were in the bottom pile when revealed after the last trick is played because someone will often click the "end game" button right away. It would be nice if the cards were printed in the chat so we could still see what they were even after the game has ended.

**Comment by rbtying** [comment]
Fixed by #229

**Comment by alvinsiu** [comment]
Hi! Thanks for making this awesome app!

We were excited to try out this feature and had enabled this setting in our family game, but the kitty did not show up in the chat. Would you mind looking into it? This happened a few minutes ago in game `#ef43c18bb40d795b` in case you have a log you can look over. Thank you!

![image](https://user-images.githubusercontent.com/1454606/92296119-2a2ec200-eeff-11ea-9e9d-1e7021c3f500.png)

**Comment by alvinsiu** [comment]
Perhaps it only displays if there are points in the kitty? The next round we played did display the kitty (with 40 points in it). The round screenshotted above had no points in the kitty.

**Comment by rbtying** [comment]
hmmm it is not expected to depend on the number of points. I'll try to repro this weekend and see what's up
