### ISSUE TITLE
some can not join game, stuck at first page

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#231]
clicking on join does nothing. 

Wondering if it has anything to do with the addition of the compression feature?

Using WiFi, some can not join. Using pure wireless LTE network, no one can join from iphone, for example.

**Comment by cai-jack** [comment]
it worked fine on Friday

**Comment by cai-jack** [comment]
more details: the browser is Safari 13

**Comment by rbtying** [comment]
ah, you're right. the issue is that safari doesn't support `arrayBuffer` apparently
