### ISSUE TITLE
out of sync game state message array when broadcast messages are sent from server rapidly?

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#238]
https://github.com/cai-jack/shengji/tree/websocket

please use this branch to observe this issue consistently:

1. please a game to finish
2. after clicking finish game, the server sends this list of broadcast messages in rapid sequence
  a). win/loss
  b). each player's rank in the new game on winning side
  c). game finish message
  d). the landlord player will start the game

On the client side:
  i) win/loss is received, and processed correctly
  ii) the first player's rank is not shown, the second is, and alternates
  iii) in a 4 player game, the game finish message is not shown, then start game message is shown.

When checking the console log messages, the message array shown two views, one view shows the message array with the odd number of messages, the other view shows the even number of messages being appended to the existing message array. In the end, only the message array with the last broadcast message (start game) from the end game broadcast are displayed in the chat box. In the 4 player game, it is the odd list that is displayed.

Seems like there are two copies of the message array that are used by the handler!

**Comment by cai-jack** [comment]
1. play a game to finish

**Comment by rbtying** [comment]
ooh, interesting! I will take a look!

Is this Safari iOS specific or on all browsers?

**Comment by cai-jack** [comment]
I observed this on Chrome. Did not try on Safari.

**Comment by cai-jack** [comment]
Chrome on MacOS
