### ISSUE TITLE
Can 5 players choose to play with 3 decks of cards?

### ISSUE THREAD

**Issue by xiaofan-iit** [rbtying/shengji#239]
I play a lot of Finding Friends. From the published rules, I cannot find if the players are free to choose the number of decks to play. I am new to Github and don't know how to submit a comment/question, therefore choosing 'Issues' to ask the question. Thanks.

**Comment by rbtying** [comment]
@xiaofan-iit 

1. I don't think there's a single fixed set of rules that everybody across the world plays this game by! Certainly, different players will choose a different number of decks. I personally usually play two decks with five players, but I have friends who play with three.
2. The game configuration settings should allow you configure five players, three friends:

![image](https://user-images.githubusercontent.com/918977/94370903-8d97b400-00a7-11eb-8ba5-fcfaf5ceb5e2.png)

and in fact any number of decks from 1 to the number of players currently in the game.

**Comment by xiaofan-iit** [comment]
Thanks so much for your quick response. We will try to play using your software soon. I am sure we will comment more later on.
