### ISSUE TITLE
Unable to join an already created room

### ISSUE THREAD

**Issue by mengdilin** [rbtying/shengji#244]
Hi,

It seems like the functionality that joins a pre-existing room is broken. To repro:

1) create a room via https://robertying.com/shengji/
2) join the room
3) share link to the room provided by `Send link to other players to allow them to join the game: <link>`
4) when clicking on the link above, a new room (a new hash for the room shows up in the ui) gets generated and clicking the join button takes me to the new room instead

I've noticed the issue as of last night

**Comment by rbtying** [comment]
ahh! that's worrying, I'll look into this.

**Comment by rbtying** [comment]
^ can you check now? I think this is fixed

**Comment by mengdilin** [comment]
Yep, it works now!
