### ISSUE TITLE
Add an option for "multi-throw evaluation policy"

### ISSUE THREAD

**Issue by xiaofan-iit** [rbtying/shengji#247]
Could we add an option that the subsequent throw that beats the longest tuple wins? For example, when the trump is spade and the rank is 2,  the first player throw [A K K] (heart), the 2nd player trumps with [5 5 A] (spade), the 3rd player trumps with [6 6 3] (spade). The 3rd player wins over the 2nd player. To generalize, one always compare with the longest tuple first, then the second longest tuple, etc.

**Comment by rbtying** [comment]
yes, that sounds feasible enough. I think the generalization is that only the longest tuple/tractor matters, right? in the example you provide, 3 < A but 66>55, so we wouldn't want to compare with the second longest tuple

**Comment by xiaofan-iit** [comment]
Thanks. If there are enough decks, we could have something like [A K K K 9 9] (heart) for the 1st player, [5 5 5 Q Q A] (spade) for the 2nd player and [5 5 5 A A 4] (spade) as the 3rd player. The 3rd player wins over the 2nd player, after comparing the longest tuple and then compare the 2nd longest. Of course, these examples do not occur often.
