### ISSUE TITLE
Multi-throw evaluation policy does not work 

### ISSUE THREAD

**Issue by xiaofan-iit** [rbtying/shengji#251]
The new choice "Subsequent throw must beat the largest component to win" under "Multi-throw evaluation policy" does not work. When selected, when the trump is 2 spade, the trick consists of 10 heart, 2 spade, 3 spade, LJ (4 players). The first player '10 heart' wins the above trick instead of LJ. Could you fix it?

**Comment by rbtying** [comment]
@xiaofan-iit does this only happen when largest-component is selected?

**Comment by xiaofan-iit** [comment]
Yes. It only happens when the recently added choice "Subsequent throw must beat the largest component to win" is selected.

**Comment by xiaofan-iit** [comment]
@rbtying Just let you know the problem still exists as of now (8:19 AM CST).  Thanks.

**Comment by rbtying** [comment]
ah, looks like my deploy failed. give me a minute.

**Comment by rbtying** [comment]
@xiaofan-iit try now?

**Comment by xiaofan-iit** [comment]
@rbtying Thanks. It works as intended now. It took sometime to create a scenario where there is multi-throw with a pair and single and there are multiple trumps. In the end, the trump with the larger pair wins instead of the larger single. Thanks.
