### ISSUE TITLE
Incorrect evaluation of highest card

### ISSUE THREAD

**Issue by m-liu** [rbtying/shengji#252]
![image](https://user-images.githubusercontent.com/1285204/99141285-c6133300-25fe-11eb-9d27-27bcecd8ef7f.png)

Diamond is trump suit. Find a friend with 5 people

**Comment by rbtying** [comment]
oh, this is problematic. do you have steps to reproduce?

**Comment by rbtying** [comment]
If this was the same issue as #251, please validate and close tomorrow? There are still players playing right now, so I don't want to interrupt their games.

**Comment by m-liu** [comment]
Yes actually! I think it's the same issue. Closing.
