### ISSUE TITLE
The ordering after a 4-tuple 

### ISSUE THREAD

**Issue by xiaofan-iit** [rbtying/shengji#255]
I think the following ordering makes sense after a player starts a trick with a 4-tuple such as [8 8 8 8] (spade): (1) if next player has a 4-tuple, then she plays the 4-tuple; (2) If one has triples, she must play one of the triples plus a single, e.g. [AAA6] ; (3) if one has no triples but has tractors, she must play one of the tractors e.g. [AAKK] (spade); (4) if none of the above, one has play two pairs; etc. Assuming no other larger 4-tuples, the winning player should be [8 8 8 8](spade). Right now, (3) and (4) are not enforced, the player can just play one pair plus to two singles.
   We only need to generalize to 5-tuple (we have never encountered 6-tuple in practice). a 5-tuple -> a 4-tuple + single -> a triple + a pair -> a triple + 2 singles -> a 2x2 tractor + a single-> 2 pairs + a single -> 1 pair + 3 singles ->...

**Comment by xiaofan-iit** [comment]
@rbtying Any comments on this issue?

**Comment by rbtying** [comment]
@xiaofan-iit sorry; will take a look. The play-ordering stuff requires some internal code refactoring, so I haven't had time to go wire all of that together.

It sounds like your proposed ordering is at least consistent, which is optimistic for a more generalizable solution. I agree that it's unlikely we'd observe 6-tuples and beyond in normal play, though perhaps worth pointing out that I thought the same about 4-tuples and 5-tuples!

**Comment by xiaofan-iit** [comment]
4-tuples have occurred in our games a few times each day we played. 5-tuples only occurred twice in practice overtime. If we could implement 4-tuple ordering, that would be great.

**Comment by rbtying** [comment]
See test [here](https://github.com/rbtying/shengji/pull/258/files#diff-af5ae88afbd370007ea203c50ac5c43ff70ca22e4ad9d57ed2e8bd20b33e6d1fR631)
