### ISSUE TITLE
Can't Dump Multiple Suits at once

### ISSUE THREAD

**Issue by joetopp** [rbtying/shengji#256]
Ran into a scenario where I had to follow suit with one card and wanted to dump low cards from multiple suits, but had to dump from only one suit.

Dumping low cards from a single suit is allowed:
![single-suit-dump](https://user-images.githubusercontent.com/29260801/99869641-55d25780-2b92-11eb-868a-90b77987af04.png)

Dumping low cards from multiple suits is disabled for some reason:
![multi-suit-dump](https://user-images.githubusercontent.com/29260801/99869642-57038480-2b92-11eb-92e3-b51ca9723b8b.png)

**Comment by rbtying** [comment]
Thanks for filing this! In this case, I think the game is operating as expected: the trick is lead with a 4-tuple in trump, so you need to play 4 cards in the trump suit if you have them. In your second image, you have 3 trump cards (C6, C9, LJ) and one non-trump card (H3) in the proposed play; however, you have 3 other trump cards you could play (C2, C10, CQ).

Does that make sense?

P.S. The "?" icon should explain what the legal follows are for the current trick.
