### ISSUE TITLE
new bug for trumping

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#259]
![Screen Shot 2020-11-24 at 7 48 55 PM](https://user-images.githubusercontent.com/4054100/100181057-561e6b80-2e8e-11eb-9bc1-32a0170dbc34.png)

trump is Diamond, rank 5
player 1 played club AK, player 2 trumped with 5 A, player 3 trumped with LJ 5. Player should have won this hand. However,
player 1 actually won the hand!

This looks like a fresh bug

**Comment by rbtying** [comment]
It looks like this is only an issue when the throw evaluation policy is set to trick-unit-length -- digging more into it now
