### ISSUE TITLE
Add possibility to overturn your own bid with double trump in a separate suit

### ISSUE THREAD

**Issue by lolzviv** [rbtying/shengji#263]
If you're currently winning the bid, but have the possibility for a higher bid in a separate suit, it doesn't show up as an option to overturn yourself

![image](https://user-images.githubusercontent.com/75152236/100493541-61c39980-30fd-11eb-91ee-00819bd0d7ff.png)
![image](https://user-images.githubusercontent.com/75152236/100493544-6720e400-30fd-11eb-8ac8-cf134c94c4e1.png)

**Comment by rbtying** [comment]
Thanks for reporting!

In this case, the rule set(s) I am familiar with do not allow you to overturn your own bid, only to reinforce it.

If that's not the way you play, we can look at putting the behavior behind a game setting. I'm always open to pull requests!

**Comment by jzligithub** [comment]
Have never played with the option to overturn yourself in a different suit, but do normally play with the option to reinforce yourself AFTER you have been overturned (instead of only preemptively reinforce).  e.g. you bid spade king, opponent bids two heart kings, you can choose to bid a second spade king to overturn (until bottom cards are picked up).  Doesn't dramatically change the game but would be a nice variant to have

**Comment by lolzviv** [comment]
It's always fun to see the different house rules -- I think both would be
interesting variants to add, would definitely influence the strategy in the
beginning

**Comment by lolzviv** [comment]
In a similar vein -- is the default ruleset that you can only bid with once with a suit (other than reinforcing). For example, Person A bids single spades, Person B overturns with double in another suit -- however even if Person A has double Jokers, A can't overturn Person B because they already bid once in Spades?  

![image](https://user-images.githubusercontent.com/75152236/102002749-5cea1280-3cc5-11eb-88af-5816c8f9ad8d.png)

**Comment by rbtying** [comment]
The default doesn't restrict you to only bidding once with a suit, but it does require that the number of cards you're bidding with to increase over the previous bid (or if you are bidding with jokers, to have at least the same number)
