### ISSUE TITLE
bug on trump ranking for trumping over a non trump suite

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#264]
![E46C410E-3061-4A5D-ABB9-D38E18578156_1_105_c](https://user-images.githubusercontent.com/4054100/100495139-52dce700-30fd-11eb-81a9-6d1559b34ea0.jpeg)

trump is 6 heart. David's hand should have won the round when trumping over the suite of 3 spades

**Comment by rbtying** [comment]
Thanks for reporting!

Do you happen to know what game settings you were playing with? Under the default settings (throw evaluation policy of beat-all), this is the expected behavior

**Comment by cai-jack** [comment]
I will ask. Which setting controls this policy?

**Comment by cai-jack** [comment]
Never mind. I assume it is under the throw evaluation policy?

**Comment by cai-jack** [comment]
they did play under the default setting
