### ISSUE TITLE
Add option so that it is not mandatory to play a pair into a pair (when possible)

### ISSUE THREAD

**Issue by Veikun** [rbtying/shengji#265]
Currently, if a pair is played, other players must also play a pair if they have one. It would be nice to have a game option where this rule is disabled.

Thank you!

**Comment by rbtying** [comment]
@Veikun, is this an accurate framing of the rule that you would like:

If trick is started with a particular trick-format, all other players are required to play as many cards as they can in that suit (up to the number in the trick-format). If they have no cards in the suit, and they play cards which match the format in trump, they win. No requirement is made to best-effort match the trick format within the suit (e.g. no play can draw out any other play, unless the following player has insufficient cards in the suit)

**Comment by Veikun** [comment]
Yes that tracks! As a concrete example, say trump is 2♠️. 

Current play:
(9♥ 9♥) 

My hand:
4♥ 5♥ 7♥ 7♥ 5♠️ 

In the current implementation, (7♥ 7♥) is the only valid play. Under this proposal, (4♥ 5♥), or any other combination of two hearts would also be valid.

**Comment by jzligithub** [comment]
Would love this - changes the game significantly and is how my friends normally play

**Comment by kevinzli17** [comment]
+1 this would be absolutely great
