### ISSUE TITLE
Display the whole score and score distribution on the top.

### ISSUE THREAD

**Issue by FangSD** [rbtying/shengji#275]
the score is the most important information. Most time, we need scroll down to see the score. and the score is not very intuitive.
just need simple status display the score distribution on the top so we can have quick view. the simplest is to show three total score: score has not been played out yet (so it will start with 100, and decrease to 0); total score received by each side.

**Comment by mwilbz** [comment]
Is this resolved by https://github.com/rbtying/shengji/pull/280 ?

**Comment by rbtying** [comment]
It seems to be, based on FangSD's comment in #277! Fang did suggest that we also add a way to see the current score

> The score bar is very nice. Could you show the actual score on the score bars? when the label closing to the break point, it's little bit hard to tell 395 or 400 or 405.
like this. see attached image.

but I'm not sure how that will look visibly (attached image didn't make it to GitHub :()

Thank you for working on it!

**Comment by FangSD** [comment]
Robert, I’m sure you fixed it. I will test it when we play it on weekend. Thanks.

Fang He

On Jan 25, 2021, at 1:23 PM, Robert Ying <notifications@github.com> wrote:

﻿

It seems to be, based on FangSD's comment in #277<https://github.com/rbtying/shengji/issues/277>! Fang did suggest that we also add a way to see the current score

The score bar is very nice. Could you show the actual score on the score bars? when the label closing to the break point, it's little bit hard to tell 395 or 400 or 405.
like this. see attached image.

but I'm not sure how that will look visibly (attached image didn't make it to GitHub :()

Thank you for working on it!

**Comment by FangSD** [comment]
thanks，the score number works great

Fang He

On Jan 28, 2021, at 10:01 AM, Robert Ying <notifications@github.com> wrote:

﻿

Closed #275<https://github.com/rbtying/shengji/issues/275>.
