### ISSUE TITLE
finish a game before all cards played out

### ISSUE THREAD

**Issue by FangSD** [rbtying/shengji#277]
Sometimes, in the middle of the game, we already know the game outcome. So we want to complete this game and start next one, is there such feature existing?

**Comment by rbtying** [comment]
There isn't presently something like this, although you can approximately do it by resetting the game and then setting the ranks/landlord appropriately.

Curious: is this more about the case where there aren't enough points left in the game to change the outcome, or is it when you "know" a certain player will win (e.g. they have the highest remaining cards)

(the latter case is harder to model)

**Comment by FangSD** [comment]
Hello Robert,

Thanks for all the enhancements. The user case to finish game early works great.
For finish game early, can you add one confirmation before finish the game? we could accidently finish game but want to change a final confirmation.

The score bar is very nice. Could you show the actual score on the score bars? when the label closing to the break point, it's little bit hard to tell 395 or 400 or 405.
like this. see attached image.

Thanks.


Fang
________________________________
