### ISSUE TITLE
Beep button does not work

### ISSUE THREAD

**Issue by cmanaog** [rbtying/shengji#283]
## Issue Summary
When hitting the bell, the sound no longer plays. Additionally it disconnects you if you press  the bell too many times.

##  Steps to reproduce:
1) Begin a game 
2) Press the bell button
3) Observe that the BEEP is no longer sent to chat; also observe no bell is played
4) If you press the button enough times, it may  disconnect you

My friends and I love this feature.

**Comment by rbtying** [comment]
...oops. but also, this is hilarious

**Comment by cmanaog** [comment]
Hahahaha resolved, thanks so much!
