### ISSUE TITLE
make end game game as an option

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#285]
as it is now, the kitty is not revealed in the chat area. and the remaining cards are not shown either. It does not have the feeling of the game goes to a completion. It is better to make it an option (as I typed, I was told the question to end game early showed up one some player's screen, not not on all). Regardless, it is better to make it an option instead.

**Comment by rbtying** [comment]
hmm, what do you mean?

the most recent change should only have made it possible to finish the game early, not forced the behavior -- maybe the button should be labeled differently?

**Comment by cai-jack** [comment]
I now understand how this work. the finish game button becomes active when a game can end early. At the least, show all the remaining unplayed cards in the card, along with the revealed kitty in the chat area, so that people can verify on their own. Does that work?
