### ISSUE TITLE
[Feature Request] Add a ready check button

### ISSUE THREAD

**Issue by cmanaog** [rbtying/shengji#296]
Small QoL feature, it would be nice to have a button that anyone can press that pings people with the bell sound and asks if they are ready. 

Sometimes I drop a link in a chat and I wait as people slowly shuffle in, so when we have enough I'm not sure if everyone is looking at the tab or not.

**Comment by rbtying** [comment]
@cmanaog is the idea here to have a broadcast-bell type thing? or something more involved

**Comment by cmanaog** [comment]
A broadcast bell would probably work, as it would make people come to the tab and I could just type in the chat to see if they're ready.

But a more ideal solution would be to press a button and have a prompt show up asking people if they're ready (and their response can show up in the message log). If you've ever played an MMO like FFXIV or WoW, it'd be similar to the ready check there.
