### ISSUE TITLE
Issues with End-Game Option and Tractor Play

### ISSUE THREAD

**Issue by TractorPlayer** [rbtying/shengji#301]
Hi Robert,

Great job and a million thanks!

A couple of issues or observations:

1. I don't believe the end-game option considers the possibility of the points in the base cards being multipled when the attacking team wins the last trick with a pair or more cards. Therefore presenting end-game option can be a faulty signal. Please consider fixing this issue. Frankly there is no easy way to fix this without leaking information on points in the basecards!!
2. When someone plays a tractor say 5566, the system allows other players to play a triple with a single card (say 6668) to save a second pair. I don't know if this is intended or it's a bug. In our ruleset, if you have a triple and a pair when someone leads with a tractor, you must play the pair regardless, and you can choose not to play the triple. Please consider fixing this issue or adding the option to force the pair being played in this situation.
Please let me know how I can be of help. Again, great job and thanks a lot.

**Comment by rbtying** [comment]
> I don't believe the end-game option considers the possibility of the points in the base cards being multipled when the attacking team wins the last trick with a pair or more cards. Therefore presenting end-game option can be a faulty signal. Please consider fixing this issue. Frankly there is no easy way to fix this without leaking information on points in the basecards!!

Yeah, this is pretty hard, since as you said anything better leaks information on the points in the bottom, but in an indeterminate way. The current implementation asks to confirm for that reason. Do you think it would be better to have an option to turn off the end-game-early behavior? If so, that's pretty easy to add.

> When someone plays a tractor say 5566, the system allows other players to play a triple with a single card (say 6668) to save a second pair. I don't know if this is intended or it's a bug. In our ruleset, if you have a triple and a pair when someone leads with a tractor, you must play the pair regardless, and you can choose not to play the triple. Please consider fixing this issue or adding the option to force the pair being played in this situation.

This one is a bit surprising, though I don't have a test written for this. I'd expect the 5566 to generate a requirement of [2, 2] (two consecutive pairs), which should decompose to [2], [2] and require the two-pair play before the triple (the triple can only match [2], [1], [1] -- see the decompositions [here](https://github.com/rbtying/shengji/blob/master/core/src/ordered_card.rs#L580)

If you have the time, I'd welcome a failing test

**Comment by TractorPlayer** [comment]
Hi Robert, 

Thanks for the quick reply. On the first issue, I suggest the following easy fix: present the end-game option only to the landloard and only if there is no point in the base. This way it adds some convenience but won't leak any information since only the landlord know the base.

On the second issue, I personally experience the following (a couple of times actually): opponent leads 5566, I have 222 and KK but the system allowed to play 2227 therefore saving KK. You seem to agree with me that KK must be played in this situation.

I'm happy to help you test, but not sure how. I'm generally available 7pm-10pm EST.

**Comment by TractorPlayer** [comment]
{
  "gameState": {
    "Initialize": {
      "propagated": {
        "players": [
          {
            "id": 0,
            "name": "CK",
            "level": "2",
            "metalevel": 1
          }
        ],
        "observers": [],
        "landlord": null,
        "max_player_id": 1,
        "num_games_finished": 0,
        "game_mode": "Tractor",
        "hide_landlord_points": false,
        "kitty_size": null,
        "friend_selection_policy": "Unrestricted",
        "multiple_join_policy": "Unrestricted",
        "num_decks": null,
        "special_decks": [],
        "landlord_emoji": null,
        "chat_link": null,
        "advancement_policy": "Unrestricted",
        "kitty_penalty": "Power",
        "throw_penalty": "TenPointsPerAttempt",
        "hide_played_cards": false,
        "kitty_bid_policy": "FirstCard",
        "kitty_theft_policy": "NoKittyTheft",
        "trick_draw_policy": "LongerTuplesProtected",
        "throw_evaluation_policy": "TrickUnitLength",
        "first_landlord_selection_policy": "ByWinningBid",
        "bid_policy": "GreaterLength",
        "bid_reinforcement_policy": "ReinforceWhileEquivalent",
        "joker_bid_policy": "BothTwoOrMore",
        "should_reveal_kitty_at_end_of_game": false,
        "play_takeback_policy": "AllowPlayTakeback",
        "bid_takeback_policy": "NoBidTakeback",
        "game_shadowing_policy": "AllowMultipleSessions",
        "game_start_policy": "AllowAnyPlayer",
        "game_scoring_parameters": {
          "step_size_per_deck": 20,
          "step_adjustments": {},
          "num_steps_to_non_landlord_turnover": 2,
          "deadzone_size": 1,
          "truncate_zero_crossing_window": true,
          "bonus_level_policy": "BonusLevelForSmallerLandlordTeam"
        },
        "hide_throw_halting_player": true
      }
    }
  },
  "settings": {
    "fourColor": false,
    "showCardLabels": true,
    "showLastTrick": true,
    "beepOnTurn": true,
    "reverseCardOrder": false,
    "unsetAutoPlayWhenWinnerChanges": false,
    "showTrickInPlayerOrder": false,
    "svgCards": true,
    "separateCardsBySuit": false,
    "disableSuitHighlights": false,
    "suitColorOverrides": {},
    "playDrawCardSound": false,
    "showDebugInfo": true
  },
  "roomName": "5b5da1ef0debcb74"
}

**Comment by rbtying** [comment]
Hi @TractorPlayer , can you open new issues for each thing?

> Also, I forgot to mention a third possible bug: In the difficulty setting I chose the "10 point penalty per bad throw" option, but I don't believe it actually works. On multiple occasions players from both sides did bad throw, but I never observed any points deducted.

when your group makes bad throws, do you keep playing cards, or do you take back the throw? if you take back the throw with the take back button, it won't apply the penalty -- you can actually keep playing; the small cards are visible but aren't part of the trick format. you can also disable taking back plays.

**Comment by TractorPlayer** [comment]
Thanks for the clarification on penalty for bad throw. 

Did you already fix the second issue? We were playing just now and I was not allowed to play a triple to save a second pair when someone played a tractor.

**Comment by rbtying** [comment]
> Thanks for the clarification on penalty for bad throw.
> 
> Did you already fix the second issue? We were playing just now and I was not allowed to play a triple to save a second pair when someone played a tractor.

I haven't changed anything recently, but there were changes about two months ago -- maybe that fixed the issue?

**Comment by TractorPlayer** [comment]
> > Thanks for the clarification on penalty for bad throw.
> > Did you already fix the second issue? We were playing just now and I was not allowed to play a triple to save a second pair when someone played a tractor.
> 
> I haven't changed anything recently, but there were changes about two months ago -- maybe that fixed the issue?

The issues happened very recently. I will print the screen and dump the setting next time when I encounter the 2nd issue (triples in place of two pairs).
