### ISSUE TITLE
System allowed triple in place of two pairs when led by tractor

### ISSUE THREAD

**Issue by TractorPlayer** [rbtying/shengji#315]
When someone plays tractor  AAKK, I have 333 and 10 10 7, the system allowed me to play 3337, while the system should force me to play 10 10. 

{
  "gameState": {
    "Initialize": {
      "propagated": {
        "players": [
          {
            "id": 3,
            "name": "P6",
            "level": "Q",
            "metalevel": 2
          },
          {
            "id": 5,
            "name": "P1",
            "level": "5",
            "metalevel": 1
          },
          {
            "id": 6,
            "name": "P2",
            "level": "Q",
            "metalevel": 1
          },
          {
            "id": 4,
            "name": "P3",
            "level": "5",
            "metalevel": 1
          },
          {
            "id": 2,
            "name": "P4",
            "level": "Q",
            "metalevel": 2
          },
          {
            "id": 7,
            "name": "P5",
            "level": "5",
            "metalevel": 1
          }
        ],
        "observers": [
          {
            "id": 1,
            "name": "P7",
            "level": "A",
            "metalevel": 2
          },
          {
            "id": 0,
            "name": "P8",
            "level": "2",
            "metalevel": 2
          }
        ],
        "landlord": 4,
        "max_player_id": 8,
        "num_games_finished": 20,
        "game_mode": "Tractor",
        "hide_landlord_points": false,
        "kitty_size": 6,
        "friend_selection_policy": "Unrestricted",
        "multiple_join_policy": "Unrestricted",
        "num_decks": 4,
        "special_decks": [],
        "landlord_emoji": null,
        "chat_link": null,
        "advancement_policy": "FullyUnrestricted",
        "kitty_penalty": "Power",
        "throw_penalty": "TenPointsPerAttempt",
        "hide_played_cards": false,
        "kitty_bid_policy": "FirstCard",
        "kitty_theft_policy": "NoKittyTheft",
        "trick_draw_policy": "LongerTuplesProtected",
        "throw_evaluation_policy": "TrickUnitLength",
        "first_landlord_selection_policy": "ByWinningBid",
        "bid_policy": "GreaterLength",
        "bid_reinforcement_policy": "ReinforceWhileEquivalent",
        "joker_bid_policy": "BothTwoOrMore",
        "should_reveal_kitty_at_end_of_game": true,
        "play_takeback_policy": "AllowPlayTakeback",
        "bid_takeback_policy": "NoBidTakeback",
        "game_shadowing_policy": "AllowMultipleSessions",
        "game_start_policy": "AllowAnyPlayer",
        "game_scoring_parameters": {
          "step_size_per_deck": 10,
          "step_adjustments": {},
          "num_steps_to_non_landlord_turnover": 4,
          "deadzone_size": 1,
          "truncate_zero_crossing_window": true,
          "bonus_level_policy": "BonusLevelForSmallerLandlordTeam"
        },
        "hide_throw_halting_player": true
      }
    }
  },
  "settings": {
    "fourColor": false,
    "darkMode": false,
    "showCardLabels": true,
    "showLastTrick": true,
    "beepOnTurn": true,
    "reverseCardOrder": false,
    "unsetAutoPlayWhenWinnerChanges": false,
    "showTrickInPlayerOrder": false,
    "svgCards": true,
    "separateCardsBySuit": false,
    "disableSuitHighlights": false,
    "suitColorOverrides": {},
    "playDrawCardSound": false,
    "showDebugInfo": true
  },
  "roomName": "5b5da1ef0debcb74"
}

**Comment by TractorPlayer** [comment]
I took a screenshot of the cards, which I can upload if necessary

**Comment by rbtying** [comment]
Hi,

Thanks for reporting! A screenshot would be helpful. 

I agree that the system should have forced you to play 10 10 3 3.

**Comment by TractorPlayer** [comment]
![image0](https://user-images.githubusercontent.com/80294451/115116165-451de600-9f66-11eb-807c-ccbe856a6310.jpeg)

**Comment by TractorPlayer** [comment]
I'm the last player

**Comment by TractorPlayer** [comment]
any ETA on when this can be fixed? thanks.

**Comment by rbtying** [comment]
Hi, sorry. I've been pretty busy with non-tractor stuff, unfortunately -- so no particular ETA at the moment. I'll see what I can do, though!

**Comment by rbtying** [comment]
OK, I took a look at this situation. This is actually expected behavior, because in your settings you have `trick_draw_policy: LongerTuplesProtected`. As a result, the system will not force you to break your triple -- even if that means you're not playing the two pairs that the tractor would require.

If you set that setting to `trick_draw_policy: NoProtections`, the system will force you to match the format properly.
