### ISSUE TITLE
repeatedly crashing - after the new commits?

### ISSUE THREAD

**Issue by cai-jack** [rbtying/shengji#334]
The server repeatedly crashed tonight, in progress games were not saved after restart. Is it caused by the recent commits?

**Comment by rbtying** [comment]
The games not being saved is weird. I will need to check logs and see what's going on there.

This is likely instability because I moved the game to another server -- sorry about that!

**Comment by rbtying** [comment]
Aha. I figured this out -- the issue is that the new server's nginx set `proxy_read_timeout` to 60s (default), which timed out the websocket connection. I have updated this to 3600s, as was previously set.
