### ISSUE TITLE
[BUG] Kitty is always visible at the bottom of the screen

### ISSUE THREAD

**Issue by Dorenavant** [rbtying/shengji#336]

**Comment by rbtying** [comment]
@Dorenavant Do you mind sending a screenshot of what the issue is, along with what your settings are?

**Comment by rbtying** [comment]
Fixed by https://github.com/rbtying/shengji/commit/90bbde61160a1db85ed9279b43443bf03b69002f

**Comment by Dorenavant** [comment]
Thanks for the quick fix :) cheers
