### ISSUE TITLE
Wrong trick winner after taking back last play

### ISSUE THREAD

**Issue by czhang23** [rbtying/shengji#347]
First, thank you for making this.  We found this is very enjoyable!

Below is the log.

In last play, Yang should have won the trick after the new play.  But S won the play.  In the attached image, even the log says S won the play, the score won by S&Hook is only 75.  But, in Yang's hand, NJ is not there any more.

BTW, Lin clicked the Finish Trick.

![Shengji](https://user-images.githubusercontent.com/19149801/152629260-dafa3234-73e0-4df6-a6d3-4b5a08b94de1.PNG)

GAME: Lin started the game

GAME: S bid 6♦

GAME: Yang played J♣J♣

GAME: Hook played A♣A♣

GAME: Lin played 4♣4♣

GAME: S played 5♣9♣

GAME: Hook wins the trick and gets 5 points

GAME: Hook played A♠

GAME: Lin played 2♠

GAME: S played K♠

GAME: Yang played 2♠

GAME: Hook wins the trick and gets 10 points

GAME: S is being shadowed

GAME: Hook played Q♣Q♣

GAME: Lin played K♣K♣

GAME: S played 7♦7♦

GAME: Yang played 2♣2♣

GAME: S wins the trick and gets 20 points

GAME: S played 2♥2♥3♥3♥

GAME: Yang played 3♠9♠7♥7♥

GAME: Hook played J♥J♥A♥A♥

GAME: Lin played 5♥9♥10♥K♥

GAME: S wins the trick and gets 25 points

GAME: S played 2♦

GAME: Yang played 6♠

GAME: Hook played HJ

GAME: Lin played 3♦

GAME: Hook wins the trick, but gets no points :(

GAME: Hook played 7♣7♣

GAME: Lin played 3♣8♣

GAME: S played 3♠5♠

GAME: Yang played J♠Q♠

GAME: Hook wins the trick and gets 5 points

GAME: Hook played 8♣10♣

GAME: Lin played 4♠7♠

GAME: S played 8♦6♦

GAME: Yang played 2♦10♦

GAME: Yang took back their last play

GAME: Yang played 2♦HJ

GAME: S wins the trick and gets 10 points

**Comment by rbtying** [comment]
Thanks for filing this bug report! It looks like you may have been playing the game using the "throw must beat all parts" setting. So, because S played 8d6d, and Yang played 2dHJ, the 2d was smaller than 8d and smaller than 6d, so S would win the trick. If Yang had played 7d9d or higher (so that there was a card higher than each card), then Yang would have won.

Please let me know if that's not the setting you were playing with. That is the default. It can be changed to beating the highest card, or beating the biggest part.

**Comment by czhang23** [comment]
Indeed.  We overlooked the settings when we check it.  It is really complicated when we realized that there are so many varieties.  It is amazing this project can handle most of them.  Thanks for your reply!

**Comment by czhang23** [comment]
2nd thought.

In case of 44K vs 55J, of course we need 55A to beat 44K.

In our case, 2/10 vs 2HJ, 2HJ should beat 2/10.

Reason 1, 2/10 cannot be thrown if there is any card is bigger.  Think about 2/10 vs 2A.
Reason 2, 2/10 doesn't have two components.  It is one component.  Within one component, beating highest card is good enough.

Seems the way we need is a combined setting, i.e.
Within component, beat highest card (or pair, or tuple, or tractor, and so on)
Cross components, beat all components.

**Comment by czhang23** [comment]
If we choose "beat the largest component",  is component defined by the original multi-throw?
AKQ, kill 44J, kill A5K, can A5K beat 44J?

**Comment by rbtying** [comment]
Good question. The largest component is defined by the original multithrow. So, in your example, A-K-Q is 3 1-tuples. So A-5-K > 4-4-J. Alternatively, if the original format is AA-K, 55-J beats 44-A
