### ISSUE TITLE
Can 4-of-a-kind or 7/8-of-a-kind be played in single deck-game or double-deck games?

### ISSUE THREAD

**Issue by czhang23** [rbtying/shengji#354]
If played without picking up the bottom cards, other players need to give 4/7/8 trump cards respectively.
If played after picking up the bottom cards, other players need to give cards in corresponding suits.

**Comment by rbtying** [comment]
This would be a pretty significant change to how tricks are currently evaluated— it’s not impossible, but it’s not clear to me how it’s supposed to work (and it’s not in the rules i play with)

can you provide more detail?

**Comment by czhang23** [comment]
It requires big change and it doesn't happen often.  Forget it.
