### ISSUE TITLE
Request: Add Option to be able to make one player to be "double" friends

### ISSUE THREAD

**Issue by blu-world** [rbtying/shengji#390]
Here is the situation for this: when there are six people playing the Finding Friend, there should be two friends for the landlord and supposedly the landlord calls the 1st Spade A and the 1st Club A as friends. Now if one player played Spade A and become the 1st friend, then later he was forced to play the Club A (as the 1st player) then he would be "double" friends and it become 4 players against 2 players now. 
This is  making the players to be careful of what to play when it is possible to have this kind consequences.
Thx!

**Comment by rbtying** [comment]
@blu-world What you are requesting is the default behavior, and you need to explicitly set the setting which disallows multiple-joins to prevent it.

Perhaps take a look at the game settings and see what you have set before starting the game?
