### ISSUE TITLE
Playing Finding Friends - somehow the player didn't play the "friend" card and the player were become the "friend" anyway.

### ISSUE THREAD

**Issue by blu-world** [rbtying/shengji#391]
We have six players (playing 4 decks of card) and the landlord calls the 1st Diamond A and the 1st Spade A as friends. When we played couple hands of Spades without anyone played Spade A and one of the player became the 1st "friend" anyway as if the player played Spade A and that player doesn't even has Spade A in hand. The Diamond A was still displayed as the next friend. 
Although I can't remember exact cards played for that hand. Maybe when that happened again, will try to report back.
Thx.

**Comment by rbtying** [comment]
@blu-world the next time this occurs, please send a screenshot of the chat log (which logs individual actions) and ideally the game debug JSON (you can turn this on from the settings gear)
