### ISSUE TITLE
[Bug] "Can only play with even number of players" shows up repeatedly (stacked messages)

### ISSUE THREAD

**Issue by jamesylgan** [rbtying/shengji#95]

**Comment by rbtying** [comment]
@jamesylgan does this show up repeatedly even when only pressed once? or is the issue that it shows up one time per click?

**Comment by jamesylgan** [comment]
I think it ends up being one time per click (was not thoroughly tested, just people spamming buttons :P) - one message would probably suffice though, or editing the message to (x1, x2, x3)

**Comment by jamesylgan** [comment]
It can get a bit unwieldy for the player who gets the messages though.

I'm also wondering why only the person who is "kicked out of the game" gets the message - seems like all players should get the message?

**Comment by rbtying** [comment]
Yeah, the error UI can definitely be improved for this kind of case. It should only affect the player clicking a lot, though, so the impact seems localized.

c.f. kicks -- yeah, we can send a game message for that. Do you mind opening a new issue?
