### ISSUE TITLE
Throttle beeps to 1/second rather than 2/second

### ISSUE THREAD

**Issue by jamesylgan** [rbtying/shengji#96]
Our group found some joy in spamming beeps, but it should probably be throttled a tad (doesn't currently seem to be any limit). I'm not too familiar with React, but seems like there's a few decently easy ways to unmount the beeper for a second or two.

Related bug: sending too many beeps too quickly seems to cause the beep sender in question to need to refresh the page in order to play their next hand.

**Comment by rbtying** [comment]
Hm. The beeps are throttled to a beep every half second. Which is possibly not enough of a throttle...

We can update this to a beep every second, perhaps?

I'm not sure what's going on with the disconnect when sending too many beeps too quickly -- do you mind capturing a console log when that happens?

**Comment by jamesylgan** [comment]
I looked for where it was getting throttled but couldn't find it - also it seemed like it could have been more than a beep every half second (maybe because we had lots of people spamming? Or is that start of one beep -> start of another beep throttle? Didn't seem like half a second between end of beep and start of next beep, but this could just be a perception thing from it being a pretty low throttle)

Next time we're playing I'll do that and update here:)

**Comment by rbtying** [comment]
https://github.com/rbtying/shengji/blob/master/frontend/src/websocketHandler.ts#L61

This is where the throttle is set. The observed difference would be about 300ms, since the beep runs for 200ms...

**Comment by jamesylgan** [comment]
Ah, cool. This issue should probably be closed and replaced (or edited) to "longer beep throttle"
